import { useEffect, useState } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { request } from './api'
import { PageHeader } from './App'

const kinds = [
  ['statuses','Статусы','Этапы обработки обязательства'],['cost_categories','Статьи затрат','Категории управленческого учёта'],['priorities','Приоритеты','Уровни очередности'],['urgencies','Срочность','Маркировка срочных платежей'],['legal_entities','Юридические лица','Организации группы'],['responsibles','Ответственные','Сотрудники, ведущие обязательства'],['account_types','Признаки учёта','ОМС и коммерция'],['counterparties','Контрагенты','Единый справочник поставщиков'],
]
export default function References({notify}){const [data,setData]=useState({});const [active,setActive]=useState('statuses');const [value,setValue]=useState('');const load=()=>request('/api/references').then(setData).catch(e=>notify(e.message,'error'));useEffect(load,[]);const add=async e=>{e.preventDefault();if(!value.trim())return;try{await request(`/api/references/${active}`,{method:'POST',body:JSON.stringify({value})});setValue('');notify('Значение добавлено');load()}catch(e){notify(e.message,'error')}};const remove=async id=>{if(!confirm('Убрать значение из справочника? Существующие записи реестра сохранятся.'))return;try{await request(`/api/references/${active}/${id}`,{method:'DELETE'});notify('Значение убрано');load()}catch(e){notify(e.message,'error')}};const current=kinds.find(k=>k[0]===active);return <div className="page"><PageHeader eyebrow="Настройки" title="Справочники" subtitle="Единые значения для выпадающих списков реестра"/><div className="settings-layout"><aside className="settings-nav">{kinds.map(([key,label,desc])=><button key={key} className={active===key?'active':''} onClick={()=>setActive(key)}><strong>{label}</strong><span>{desc}</span><i>{(data[key]||[]).length}</i></button>)}</aside><section className="panel reference-panel"><div className="reference-head"><div><h2>{current[1]}</h2><span>{current[2]}</span></div><form onSubmit={add}><input placeholder="Новое значение" value={value} onChange={e=>setValue(e.target.value)}/><button className="primary"><Plus size={17}/>Добавить</button></form></div><div className="reference-list">{(data[active]||[]).map((item,index)=><div key={item.id}><span>{String(index+1).padStart(2,'0')}</span><strong>{item.value}</strong><button onClick={()=>remove(item.id)}><Trash2 size={16}/></button></div>)}</div></section></div></div>}
