import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, Download, FileUp, Filter, MoreHorizontal, Pencil, Plus, RotateCcw, Search, Trash2, X } from 'lucide-react'
import { download, request } from './api'
import { money, PageHeader, shortDate } from './App'

const emptyFilters = { q: '', account_type: '', legal_entity: '', cost_category: '', priority: '', responsible: '', status: '', urgency: '', planned_from: '', planned_to: '', overdue: '' }
const refMap = { account_type: 'account_types', legal_entity: 'legal_entities', cost_category: 'cost_categories', priority: 'priorities', responsible: 'responsibles', status: 'statuses', urgency: 'urgencies', counterparty: 'counterparties' }
const labels = { account_type: 'Признак учёта', legal_entity: 'Юрлицо', cost_category: 'Статья затрат', priority: 'Приоритет', responsible: 'Ответственный', status: 'Статус', urgency: 'Срочность' }

export default function Registry({ user, notify }) {
  const [data, setData] = useState({ items: [], total: 0, page: 1, page_size: 50 })
  const [refs, setRefs] = useState({})
  const [filters, setFilters] = useState(emptyFilters)
  const [page, setPage] = useState(1)
  const [sort, setSort] = useState({ key: 'updated_at', order: 'desc' })
  const [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState(null)
  const [selected, setSelected] = useState([])
  const [bulkOpen, setBulkOpen] = useState(false)
  const importRef = useRef()

  useEffect(() => { Promise.all([request('/api/references'), request('/api/saved-view')]).then(([r, saved]) => { setRefs(r); if (saved && Object.keys(saved).length) setFilters({ ...emptyFilters, ...saved }) }).catch(e => notify(e.message, 'error')) }, [])
  const query = useMemo(() => { const params = new URLSearchParams({ page, page_size: 50, sort: sort.key, order: sort.order }); Object.entries(filters).forEach(([k, v]) => v && params.set(k, v)); return params.toString() }, [filters, page, sort])
  const load = () => { setLoading(true); request(`/api/obligations?${query}`).then(setData).catch(e => notify(e.message, 'error')).finally(() => setLoading(false)) }
  useEffect(() => { const timer = setTimeout(load, 220); return () => clearTimeout(timer) }, [query])
  useEffect(() => { const timer = setTimeout(() => request('/api/saved-view', { method: 'PUT', body: JSON.stringify(filters) }).catch(() => {}), 700); return () => clearTimeout(timer) }, [filters])
  const setFilter = (key, value) => { setFilters(old => ({ ...old, [key]: value })); setPage(1) }
  const totalPages = Math.max(1, Math.ceil(data.total / data.page_size))
  const allSelected = data.items.length > 0 && data.items.every(item => selected.includes(item.id))
  const toggleAll = () => setSelected(allSelected ? selected.filter(id => !data.items.some(i => i.id === id)) : [...new Set([...selected, ...data.items.map(i => i.id)])])
  const save = async values => { try { if (values.id) await request(`/api/obligations/${values.id}`, { method: 'PATCH', body: JSON.stringify(strip(values)) }); else await request('/api/obligations', { method: 'POST', body: JSON.stringify(strip(values)) }); notify(values.id ? 'Изменения сохранены' : 'Обязательство добавлено'); setEditing(null); load() } catch (e) { notify(e.message, 'error') } }
  const remove = async id => { if (!confirm('Удалить обязательство? Отменить это действие нельзя.')) return; try { await request(`/api/obligations/${id}`, { method: 'DELETE' }); notify('Запись удалена'); load() } catch (e) { notify(e.message, 'error') } }
  const importFile = async event => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append('file', file); try { const result = await request('/api/obligations/import.xlsx', { method: 'POST', body }); notify(`Импортировано строк: ${result.imported}`); load() } catch (e) { notify(e.message, 'error') } finally { event.target.value = '' } }
  const doSort = key => setSort(current => ({ key, order: current.key === key && current.order === 'asc' ? 'desc' : 'asc' }))
  return <div className="page registry-page">
    <PageHeader eyebrow="Рабочая область" title="Реестр обязательств" subtitle={`${data.total.toLocaleString('ru-RU')} записей с учётом фильтров`} actions={<>{user.role === 'admin' && <><input ref={importRef} type="file" accept=".xlsx" hidden onChange={importFile}/><button className="secondary" onClick={() => importRef.current.click()}><FileUp size={17}/>Импорт</button></>}<button className="secondary" onClick={() => download(`/api/obligations/export.xlsx?${query}`, 'Реестр обязательств.xlsx')}><Download size={17}/>Excel</button>{user.role !== 'viewer' && <button className="primary" onClick={() => setEditing({})}><Plus size={18}/>Добавить</button>}</>}/>
    <section className="filter-panel">
      <div className="search-box"><Search size={18}/><input placeholder="Контрагент, счёт, комментарий…" value={filters.q} onChange={e => setFilter('q', e.target.value)}/>{filters.q && <button onClick={() => setFilter('q', '')}><X size={15}/></button>}</div>
      {['legal_entity','status','cost_category','priority','responsible','urgency','account_type'].map(key => <FilterSelect key={key} label={labels[key]} value={filters[key]} options={refs[refMap[key]]} onChange={value => setFilter(key, value)}/>) }
      <label className="filter-date"><span>Срок с</span><input type="date" value={filters.planned_from} onChange={e => setFilter('planned_from', e.target.value)}/></label>
      <label className="filter-date"><span>по</span><input type="date" value={filters.planned_to} onChange={e => setFilter('planned_to', e.target.value)}/></label>
      <button className={`overdue-toggle ${filters.overdue ? 'active' : ''}`} onClick={() => setFilter('overdue', filters.overdue ? '' : 'true')}><Filter size={15}/>Только просроченные</button>
      {Object.values(filters).some(Boolean) && <button className="reset-filters" onClick={() => { setFilters(emptyFilters); setPage(1) }}><RotateCcw size={15}/>Сбросить</button>}
    </section>
    <section className="table-card">
      {selected.length > 0 && <div className="selection-bar"><span><Check size={16}/>{selected.length} выбрано</span>{user.role !== 'viewer' && <button onClick={() => setBulkOpen(true)}>Изменить статус и даты</button>}<button onClick={() => setSelected([])}>Снять выбор</button></div>}
      <div className="registry-table-wrap"><table className="registry-table"><thead><tr><th className="check-col"><input type="checkbox" checked={allSelected} onChange={toggleAll}/></th><SortHead label="Контрагент" field="counterparty" sort={sort} onClick={doSort}/><th>Документ</th><SortHead label="Юрлицо" field="legal_entity" sort={sort} onClick={doSort}/><th>Статья затрат</th><SortHead label="Сумма" field="amount" sort={sort} onClick={doSort}/><SortHead label="Плановая оплата" field="planned_payment_date" sort={sort} onClick={doSort}/><SortHead label="Статус" field="status" sort={sort} onClick={doSort}/><th>Срочность</th><th>Ответственный</th><th>Приоритет</th><th>Признак</th><th>Комментарий</th><th className="action-col"/></tr></thead>
      <tbody>{loading ? <SkeletonRows/> : data.items.length === 0 ? <tr><td colSpan="14"><div className="empty-state"><Search size={27}/><strong>Ничего не найдено</strong><span>Измените или сбросьте фильтры</span></div></td></tr> : data.items.map(item => <tr key={item.id} className={rowTone(item)}><td className="check-col"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(s => s.includes(item.id) ? s.filter(id => id !== item.id) : [...s, item.id])}/></td><td className="counterparty-cell"><strong>{item.counterparty || '—'}</strong><span>{shortDate(item.entry_date)}</span></td><td title={item.source_note || ''}><span className="doc-number">{item.document_number || '—'}{item.source_note && <i className="note-mark">i</i>}</span><small>{shortDate(item.document_date)}</small>{item.source_note && <small className="source-note">{item.source_note}</small>}</td><td>{item.legal_entity || '—'}</td><td className="category-cell">{item.cost_category || '—'}</td><td className="money-cell">{money(item.amount)}</td><td><span className={item.overdue ? 'date-overdue' : ''}>{shortDate(item.planned_payment_date)}</span>{item.deferment_days != null && <small>отсрочка {item.deferment_days} дн.</small>}</td><td><Status value={item.status}/></td><td><Urgency value={item.urgency}/></td><td>{item.responsible || '—'}</td><td><span className="priority">{item.priority || '—'}</span></td><td>{item.account_type || '—'}</td><td className="comment-cell" title={item.comment}>{item.comment || '—'}</td><td className="action-col">{user.role !== 'viewer' ? <div className="row-actions"><button onClick={() => setEditing(item)} title="Редактировать"><Pencil size={16}/></button>{user.role === 'admin' && <button className="danger-button" onClick={() => remove(item.id)} title="Удалить"><Trash2 size={16}/></button>}</div> : <MoreHorizontal size={18}/>}</td></tr>)}</tbody></table></div>
      <footer className="table-footer"><span>Показано {data.items.length} из {data.total.toLocaleString('ru-RU')}</span><div><button disabled={page === 1} onClick={() => setPage(p => p - 1)}><ChevronLeft size={17}/></button><span>Страница <b>{page}</b> из {totalPages}</span><button disabled={page === totalPages} onClick={() => setPage(p => p + 1)}><ChevronRight size={17}/></button></div></footer>
    </section>
    {editing && <ObligationModal item={editing} refs={refs} onClose={() => setEditing(null)} onSave={save}/>} {bulkOpen && <BulkModal count={selected.length} refs={refs} onClose={() => setBulkOpen(false)} onSave={async values => { try { await request('/api/obligations/bulk', { method: 'POST', body: JSON.stringify({ ids: selected, ...values }) }); notify('Выбранные строки обновлены'); setBulkOpen(false); setSelected([]); load() } catch (e) { notify(e.message, 'error') } }}/>} 
  </div>
}

function FilterSelect({ label, value, options = [], onChange }) { return <label className={`filter-select ${value ? 'has-value' : ''}`}><span>{label}</span><select value={value} onChange={e => onChange(e.target.value)}><option value="">Все</option>{options.map(option => <option key={option.id ?? option.value} value={option.value}>{option.value}</option>)}</select></label> }
function SortHead({ label, field, sort, onClick }) { return <th className={sort.key === field ? 'sorted' : ''} onClick={() => onClick(field)}>{label}<i>{sort.key === field ? (sort.order === 'asc' ? '↑' : '↓') : '↕'}</i></th> }
function Status({ value }) { return <span className={`status status-${slug(value)}`}>{value || 'Не указан'}</span> }
function Urgency({ value }) { return value ? <span className={`urgency urgency-${slug(value)}`}><i/>{value}</span> : <span className="muted">—</span> }
function slug(value = '') { return ({ 'Оплачено':'paid','К оплате':'to-pay','Зарегистрирован':'registered','Частично оплачено':'partial','Отменено':'cancelled','Критическая':'critical','Срочная':'urgent','Обычная':'normal' }[value] || 'empty') }
function rowTone(item) { return item.overdue ? 'row-overdue' : item.due_soon ? 'row-soon' : item.status === 'К оплате' ? 'row-to-pay' : '' }
function SkeletonRows() { return <>{Array.from({ length: 8 }).map((_, i) => <tr className="skeleton-row" key={i}>{Array.from({ length: 14 }).map((__, j) => <td key={j}><i/></td>)}</tr>)}</> }
function strip(values) { const result = { ...values }; delete result.id; delete result.created_at; delete result.updated_at; delete result.overdue; delete result.due_soon; return result }

function ObligationModal({ item, refs, onClose, onSave }) {
  const [form, setForm] = useState({ account_type:'',entry_date:new Date().toISOString().slice(0,10),counterparty:'',legal_entity:'',cost_category:'',priority:'',responsible:'',document_number:'',deferment_days:'',document_date:'',amount:'',planned_payment_date:'',approval_date:'',actual_payment_date:'',status:'Зарегистрирован',urgency:'',comment:'',source_note:'',...item })
  const set = (key, value) => setForm(old => ({ ...old, [key]: value }))
  useEffect(() => { if (form.document_date && form.deferment_days !== '' && !item.id) { const d = new Date(`${form.document_date}T00:00:00`); d.setDate(d.getDate() + Number(form.deferment_days || 0)); set('planned_payment_date', d.toISOString().slice(0, 10)) } }, [form.document_date, form.deferment_days])
  const submit = e => { e.preventDefault(); onSave({ ...form, deferment_days: form.deferment_days === '' ? null : Number(form.deferment_days), amount: form.amount === '' ? null : Number(form.amount) }) }
  return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><form className="modal obligation-modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">{item.id ? `Запись №${item.id}` : 'Новая запись'}</p><h2>{item.id ? 'Редактирование обязательства' : 'Новое обязательство'}</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="modal-body form-grid">
    <SelectField label="Признак учёта" value={form.account_type} options={refs.account_types} onChange={v => set('account_type', v)}/><Field label="Дата внесения" type="date" value={form.entry_date} onChange={v => set('entry_date', v)}/>
    <SelectField label="Контрагент" value={form.counterparty} options={refs.counterparties} editable onChange={v => set('counterparty', v)} wide/><SelectField label="Юридическое лицо" value={form.legal_entity} options={refs.legal_entities} onChange={v => set('legal_entity', v)}/>
    <SelectField label="Статья затрат" value={form.cost_category} options={refs.cost_categories} onChange={v => set('cost_category', v)} wide/><SelectField label="Приоритет" value={form.priority} options={refs.priorities} onChange={v => set('priority', v)}/>
    <SelectField label="Ответственный" value={form.responsible} options={refs.responsibles} onChange={v => set('responsible', v)}/><Field label="№ счёта / договора" value={form.document_number} onChange={v => set('document_number', v)}/><label className="field wide"><span>Условия оплаты / заметка к документу</span><textarea rows="2" value={form.source_note} onChange={e => set('source_note', e.target.value)} placeholder="Например: отсрочка 30 дней или оплата до 10 числа"/></label>
    <Field label="Дата документа" type="date" value={form.document_date} onChange={v => set('document_date', v)}/><Field label="Отсрочка, дней" type="number" value={form.deferment_days ?? ''} onChange={v => set('deferment_days', v)}/><Field label="Сумма, ₽" type="number" step="0.01" value={form.amount ?? ''} onChange={v => set('amount', v)} required/><Field label="Плановая дата оплаты" type="date" value={form.planned_payment_date} onChange={v => set('planned_payment_date', v)}/>
    <SelectField label="Статус" value={form.status} options={refs.statuses} onChange={v => set('status', v)}/><SelectField label="Срочность" value={form.urgency} options={refs.urgencies} onChange={v => set('urgency', v)}/><Field label="Дата утверждения оплаты" type="date" value={form.approval_date} onChange={v => set('approval_date', v)}/><Field label="Фактическая дата оплаты" type="date" value={form.actual_payment_date} onChange={v => set('actual_payment_date', v)}/><label className="field wide"><span>Комментарий</span><textarea rows="3" value={form.comment} onChange={e => set('comment', e.target.value)}/></label>
  </div><div className="modal-footer"><button type="button" className="secondary" onClick={onClose}>Отмена</button><button className="primary">{item.id ? 'Сохранить' : 'Добавить в реестр'}</button></div></form></div>
}
function Field({ label, value, onChange, wide, ...props }) { return <label className={`field ${wide ? 'wide' : ''}`}><span>{label}</span><input value={value ?? ''} onChange={e => onChange(e.target.value)} {...props}/></label> }
function SelectField({ label, value, options = [], onChange, wide, editable }) { return <label className={`field ${wide ? 'wide' : ''}`}><span>{label}</span>{editable ? <><input list={`list-${label}`} value={value} onChange={e => onChange(e.target.value)}/><datalist id={`list-${label}`}>{options.map(o => <option key={o.id ?? o.value} value={o.value}/>)}</datalist></> : <select value={value} onChange={e => onChange(e.target.value)}><option value="">Не выбрано</option>{options.map(o => <option key={o.id ?? o.value} value={o.value}>{o.value}</option>)}</select>}</label> }
function BulkModal({ count, refs, onClose, onSave }) { const [form,setForm]=useState({status:'',approval_date:'',actual_payment_date:''});return <div className="modal-backdrop"><div className="modal small-modal"><div className="modal-head"><div><p className="eyebrow">Массовое действие</p><h2>Изменить {count} строк</h2></div><button onClick={onClose}><X/></button></div><div className="modal-body stacked-fields"><SelectField label="Новый статус" value={form.status} options={refs.statuses} onChange={v=>setForm({...form,status:v})}/><Field label="Дата утверждения" type="date" value={form.approval_date} onChange={v=>setForm({...form,approval_date:v})}/><Field label="Фактическая дата оплаты" type="date" value={form.actual_payment_date} onChange={v=>setForm({...form,actual_payment_date:v})}/></div><div className="modal-footer"><button className="secondary" onClick={onClose}>Отмена</button><button className="primary" onClick={()=>onSave(form)}>Применить</button></div></div></div> }
